# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('numero_exterior', models.CharField(max_length=30)),
                ('numero_interior', models.CharField(blank=True, max_length=30, null=True)),
                ('Referencias', models.CharField(blank=True, max_length=30, null=True)),
                ('cp', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('grupo', models.CharField(choices=[('Gerencia', 'Gerencia'), ('Cajero', 'Cajero'), ('Repartidor', 'Repartidor')], max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
