# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171109_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='sucursal',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='empleado',
        ),
    ]
