# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171121_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(upload_to='menu'),
        ),
    ]
