# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20171122_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarro',
            name='tamano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tamanos'),
        ),
    ]
