# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_productocarro_tamano'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos_orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ordenes_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(null=True)),
                ('payment_type', models.CharField(max_length=100, null=True)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articulos_orden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ordenes_usuario'),
        ),
        migrations.AddField(
            model_name='articulos_orden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menu'),
        ),
        migrations.AddField(
            model_name='articulos_orden',
            name='tamano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tamanos'),
        ),
    ]
