# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171125_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
