# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ingredientes',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='ingredientes',
            name='precio',
        ),
        migrations.AddField(
            model_name='menu',
            name='combinada',
            field=models.BooleanField(default=False),
        ),
    ]
