# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ingredientes_productocarro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_orden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='articulos_orden',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='articulos_orden',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='ordenes_usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='productocarro',
            name='ingrediente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='articulos_orden',
        ),
        migrations.DeleteModel(
            name='ordenes_usuario',
        ),
    ]
