# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20171127_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocarro',
            name='ingrediente',
        ),
    ]
