# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_productocarro_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Direcciones'),
        ),
    ]
