# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_direcciones_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='algo',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
