# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_comentario_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='repartidor',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido_repartidor',
            name='num_pedido',
        ),
        migrations.AddField(
            model_name='pedido_repartidor',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cart'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='trabajando',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido_repartidor',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='empleado',
        ),
    ]
