# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0026_auto_20171129_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='caja_repartidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.caja_repartidor'),
        ),
    ]
