# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171109_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcciones',
            old_name='Referencias',
            new_name='referencias',
        ),
    ]
