# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171121_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='imagen',
            field=models.ImageField(default='/', upload_to='ingredientes'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(default='/', upload_to='menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
