# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cart_productocarro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanos',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
