# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20171122_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
