# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
