# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cart'),
        ),
    ]
